apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: lockedin
type: Opaque
stringData:
  POSTGRES_DB: "lockedin"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ""
  POSTGRES_PORT: "5432"
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/lockedin"