DEFAULT_PROFILE_SLUG = "default"
DEFAULT_PROFILE_NAME = "Development Profile"

DEFAULT_NOTIFICATION_TONE = "professional"
DEFAULT_TEXT_SIZE_PERCENT = 100
MIN_TEXT_SIZE_PERCENT = 75
MAX_TEXT_SIZE_PERCENT = 150
DEFAULT_DAILY_LIMIT_MINUTES = 180
