apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: lockedin
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "",
          "password": "",
          "email": "",
          "auth": ""
        }
      }
    }